version: '3.3'

secrets:
 dbpass:
   file: ./dbpass.env

services:
  stellar:
    image: stellar/quickstart:latest
    secrets:
      - dbpass
    entrypoint: ["/opt/scripts/start.sh", "dbpass", "--pubnet"]
    volumes:
      - ./scripts:/opt/scripts
      # Folder where the data is kept in Persistent Mode
      - ./opt-stellar:/opt/stellar
      # Default configs from submodule stellar/docker-stellar-core-horizon
      - ./lib/stellar-quickstart:/opt/stellar-default
    ports:
      - "8000:8000"
      - "5000:5432"
      # TODO: Remove this, the stellar-core HTTP port shouldn't be accessible
      - "11626:11626"
      # TODO: Remove this, http port used by 'getvoters'
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
