version: '3.3'

secrets:
 dbpass:
   file: ./dbpass.env

services:
  stellar:
    image: stellar/quickstart:latest
    secrets:
      - dbpass
    entrypoint: ["/opt/scripts/start.sh", "dbpass", "--pubnet"]
    volumes:
      - ./scripts:/opt/scripts
      # Folder where the data is kept in Persistent Mode
      - ./opt-stellar:/opt/stellar
      # Default configs from submodule stellar/docker-stellar-core-horizon
      - ./lib/stellar-quickstart:/opt/stellar-default
    ports:
      - "8000:8000"
      - "5000:5432"
      # TODO: Remove this, the stellar-core HTTP port shouldn't be accessible
      - "11626:11626"
      # TODO: Remove this, http port used by 'getvoters'
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]

  watcher:
    image: matheusbcomp/watcher:latest
    secrets:
      - dbpass
    environment:
      - POSTGRES_HOST=stellar
      - POSTGRES_PORT=5432
      - POSTGRES_DB=core
      - POSTGRES_USER=stellar
      - HORIZON_URL=http://stellar:8000
    entrypoint: ["/root/scripts/watcherStart.sh", "dbpass"]
    volumes:
      - ./scripts:/root/scripts
      # Map the same folder to keep both the success and error results
      - ./watcher:/root/success
      - ./watcher:/root/error
    deploy:
      placement:
        constraints: [node.role == manager]
